# Generated by Django 4.0.3 on 2022-03-27 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("events", "0002_remove_event_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="client",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.client",
            ),
            preserve_default=False,
        ),
    ]
