# Generated by Django 4.0.3 on 2022-03-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="value",
            field=models.DecimalField(
                decimal_places=4, max_digits=10
            ),
        ),
    ]
