# Generated by Django 4.0.3 on 2022-03-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_page_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="url",
            field=models.CharField(
                null=True, default=None, max_length=400
            ),
            preserve_default=False,
        ),
    ]
