# Generated by Django 4.0.3 on 2022-03-27 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_alter_page_url"),
        (
            "metadata",
            "0002_metadata_image_metadata_locale_metadata_published_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="image",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="metadata",
            name="locale",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="metadata",
            name="page",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.page",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="metadata",
            name="published_at",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="metadata",
            name="site",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
