# Generated by Django 4.0.3 on 2022-03-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "metadata",
            "0003_alter_metadata_image_alter_metadata_locale_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="author",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="image",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="keywords",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="locale",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="site",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="viewport",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
