# Generated by Django 4.0.3 on 2022-03-27 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0002_remove_metric_step_metric_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metric",
            name="title",
        ),
    ]
