# Generated by Django 4.0.3 on 2022-03-27 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_value"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="client",
        ),
        migrations.AddField(
            model_name="subscription",
            name="event",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.event",
            ),
            preserve_default=False,
        ),
    ]
