# Generated by Django 4.0.3 on 2022-03-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0002_remove_subscription_campaign_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="deleted_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
