# Generated by Django 4.0.3 on 2022-04-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_subscription_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="price",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=10
            ),
        ),
    ]
